version: '3.3'

services:
  db:
    container_name: myPostgressql
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgresDB
    ports:
      - '5432:5432'
